package com.tw;

import org.apache.poi.sl.usermodel.PictureData;
import org.apache.poi.util.IOUtils;
import org.apache.poi.xslf.usermodel.XMLSlideShow;
import org.apache.poi.xslf.usermodel.XSLFFreeformShape;
import org.apache.poi.xslf.usermodel.XSLFPictureData;
import org.apache.poi.xslf.usermodel.XSLFPictureShape;
import org.apache.poi.xslf.usermodel.XSLFSlide;

import java.awt.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URL;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zyang' at '3/2/16 10:53 PM' with Gradle 2.7
 *
 * @author zyang, @date 3/2/16 10:53 PM
 */
public class PPTCreator {
    public static void main(String[] args) throws IOException {
        //creating a new empty slide show
        XMLSlideShow ppt = new XMLSlideShow();
        XSLFSlide slide = ppt.createSlide();

//        XSLFPictureShape picShape = createPicShape(ppt, slide);

        // create shapes
        java.awt.geom.GeneralPath path = new java.awt.geom.GeneralPath();
        path.moveTo(100, 100);
        path.lineTo(200, 100);
        path.lineTo(200, 200);
        path.lineTo(300, 200);
        path.lineTo(300, 300);
//        path.closePath();

        XSLFFreeformShape shape = slide.createFreeform();
        shape.setPath(path);
        shape.setLineWidth(2);
        shape.setLineColor(Color.CYAN);

        //creating an FileOutputStream object
        File file =new File("example1.pptx");
        FileOutputStream out = new FileOutputStream(file);

        //saving the changes to a file
        ppt.write(out);
        System.out.println("Presentation created successfully");
        out.close();
    }

    private static XSLFPictureShape createPicShape(XMLSlideShow ppt, XSLFSlide slide) throws IOException {
        URL resource = PPTCreator.class.getClassLoader().getResource("server.png");
        byte[] pictureData = IOUtils.toByteArray(new FileInputStream(resource.getPath()));

        XSLFPictureData pd = ppt.addPicture(pictureData, PictureData.PictureType.PNG);
        XSLFPictureShape pic = slide.createPicture(pd);

        return pic;
    }
}
